# -*- coding: utf-8 -*-
"""Delivery Delay Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4vz6Rou_lcwcDUWW9LIZ0Rgsq75TDsl
"""

import pandas as pd
import os
import kagglehub
import sqlite3
from numpy import heaviside
# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

customer_df = pd.read_csv(os.path.join(path, "olist_customers_dataset.csv"))
geolocation_df = pd.read_csv(os.path.join(path, "olist_geolocation_dataset.csv"))
order_item_df = pd.read_csv(os.path.join(path, "olist_order_items_dataset.csv"))
order_payment_df = pd.read_csv(os.path.join(path, "olist_order_payments_dataset.csv"))
oreder_review_df = pd.read_csv(os.path.join(path, "olist_order_reviews_dataset.csv"))
oreders_df = pd.read_csv(os.path.join(path, "olist_orders_dataset.csv"))
products_df = pd.read_csv(os.path.join(path, "olist_products_dataset.csv"))
sellers_df = pd.read_csv(os.path.join(path, "olist_sellers_dataset.csv"))
product_category_name = pd.read_csv(os.path.join(path, "product_category_name_translation.csv"))
#upload the database

import sqlite3
conn = sqlite3.connect('olist.db')

oreders_df.to_sql('orders', conn, if_exists='replace', index=False)
customer_df.to_sql('customers', conn, if_exists='replace', index=False)

print("data loaded to sqlite")

oreder_review_df.to_sql('order_reviews', conn, if_exists='replace', index=False)
oreders_df.to_sql('orders', conn, if_exists='replace', index=False)
customer_df.to_sql('customers', conn, if_exists='replace', index=False)

full_analysis_query = """
SELECT
    o.order_id,
    c.customer_state,
    c.customer_city,

    JULIANDAY(o.order_delivered_carrier_date) - JULIANDAY(o.order_purchase_timestamp) AS seller_handling_days,
    JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_delivered_carrier_date) AS shipping_days,

    CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END AS is_late,

    r.review_score
FROM
    orders o
LEFT JOIN
    customers c ON o.customer_id = c.customer_id
LEFT JOIN
    order_reviews r ON o.order_id = r.order_id
WHERE
    o.order_status = 'delivered'
    AND o.order_delivered_customer_date IS NOT NULL;
"""

df_full = pd.read_sql_query(full_analysis_query, conn)

print(df_full.head())

order_item_df.to_sql('order_items', conn, if_exists='replace', index=False)
products_df.to_sql('products', conn, if_exists='replace', index=False)

full_analysis_query_v2 = """
SELECT
    o.order_id,
    c.customer_state,
    p.product_category_name,  -- 新增：商品类别
    -- 1. 物流时间特征
    JULIANDAY(o.order_delivered_carrier_date) - JULIANDAY(o.order_purchase_timestamp) AS seller_handling_days,
    JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_delivered_carrier_date) AS shipping_days,
    -- 2. 延迟标记
    CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END AS is_late,
    -- 3. 客户评价
    r.review_score
FROM
    orders o
LEFT JOIN
    customers c ON o.customer_id = c.customer_id
LEFT JOIN
    order_reviews r ON o.order_id = r.review_id  -- 建议检查关联键是否为 order_id
LEFT JOIN
    order_items oi ON o.order_id = oi.order_id   -- 连接订单明细
LEFT JOIN
    products p ON oi.product_id = p.product_id   -- 连接产品详情
WHERE
    o.order_status = 'delivered'
    AND o.order_delivered_customer_date IS NOT NULL;
"""

df_full_v2 = pd.read_sql_query(full_analysis_query_v2, conn)
print(df_full_v2.head())

state_summary = df_full.groupby('customer_state').agg({
    'is_late': 'mean',
    'review_score': 'mean',
    'shipping_days': 'mean'
}).sort_values('is_late', ascending=False)

print(state_summary.head())

from google.colab import files
df_full.to_csv('logistics_analysis_result.csv', index=False, encoding='utf-8-sig')
state_summary.to_csv('state_summary.csv', index=True, encoding='utf-8-sig')
df_full_v2.to_csv('logistics_analysis_result_v2.csv', index=False, encoding='utf-8-sig')
files.download('logistics_analysis_result_v2.csv')